# Generated by Django 4.2.1 on 2023-05-21 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_trader_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='profit_loss',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='timestamp',
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID',null=True )),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.trader')),
            ],
        ),
    ]
