# Generated by Django 4.2.1 on 2023-05-21 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0007_alter_trade_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trader',
        ),
        migrations.AddField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
