# Generated by Django 4.2.1 on 2023-05-21 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_remove_trade_trader_trade_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
        migrations.AddField(
            model_name='trade',
            name='trader',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.trader'),
            preserve_default=False,
        ),
    ]
