# Generated by Django 4.1.9 on 2023-05-22 03:47

import Dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_alter_trade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=Dashboard.models.generate_random_float, max_digits=10),
        ),
    ]
