# Generated by Django 3.0.5 on 2023-05-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_alter_trade_profit_loss'),
        ('Dashboard', '0008_alter_trade_id_alter_trade_profit_loss_and_more'),
    ]

    operations = [
    ]
