# Generated by Django 3.0.5 on 2023-05-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20230522_1138'),
        ('Dashboard', '0016_auto_20230522_1142'),
    ]

    operations = [
    ]
