# Generated by Django 4.2.1 on 2023-05-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_alter_trade_id_alter_trader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
