# Generated by Django 4.2.1 on 2023-05-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_alter_trade_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='trader_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
