# Generated by Django 4.2.1 on 2023-05-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0022_remove_trader_trader_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='trader_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
