# Generated by Django 4.2.1 on 2023-05-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0024_remove_trader_trader_id_alter_trade_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
